# Generated by Django 3.1 on 2020-08-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigsscrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='Searches',
        ),
    ]
