# Generated by Django 3.1 on 2020-08-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigsscrapper', '0002_auto_20200816_2002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Searches',
            new_name='Search',
        ),
    ]
