# Generated by Django 3.1 on 2020-08-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craigsscrapper', '0003_auto_20200816_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
